name: nasa_apod
description: "Test app using NASA APOD endpoint"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  go_router: ^14.7.2
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  injectable: ^2.5.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  retrofit_generator: ^9.1.7
  injectable_generator: ^2.7.0
  go_router_builder: ^2.7.5
  mockito: ^5.4.5

flutter:
  uses-material-design: true
